---
name: Send Daily Hope Emails

'on':
  schedule:
    # 10:20 AM UTC = 11:20 AM BST (London summer time) - TEMPORARY TEST TIME
    - cron: '20 10 * * *'
    # 10:20 PM UTC = 11:20 PM BST (London summer time) - TEMPORARY TEST TIME
    - cron: '20 22 * * *'
    # Note: During GMT (winter), these times will be 11:20 AM/PM GMT
    # TODO: Change back to 11:09 AM/PM after testing

  workflow_dispatch:  # Allow manual triggering

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send email
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "
          import sys
          sys.path.append('.')
          from main import send_email
          send_email()
          "
